name: Data Engineering CI
on:
    push:
        branches:
            - main
            - feat/*
            - fix/*

jobs:
    run-ci:
        runs-on: ubuntu-latest
        container: vighneshwed/glue4:latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                python3 -m pip install --upgrade pip
                pip3 install -r requirements.txt

            - name: Type check
              run: mypy ./ --ignore-missing-imports

            - name: Lint
              run: |
                pylint app tests jobs setup.py
                pylint app tests jobs setup.py --output pylint-report.txt

            - name: Testing
              run: |
                coverage run --source=app -m unittest discover -s tests

            - name: Test coverage report
              run: |
                coverage report
                coverage xml
